services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - DYNAMODB_REGION=us-east-1
      - DYNAMODB_TABLE=Licenses
      - DYNAMODB_ENDPOINT_URL=http://dynamodb-local:8000
      - SECRET_KEY=dev_secret_key_change_in_production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - dynamodb-local
    volumes:
      - ./app:/app/app
    networks:
      - lapsusint-network

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - "8002:8000"
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
    networks:
      - lapsusint-network

networks:
  lapsusint-network:
    driver: bridge 