version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - DYNAMODB_REGION=us-east-1
      - DYNAMODB_TABLE=Licenses
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    env_file:
      - env.production
    volumes:
      - ./app:/app/app
    restart: unless-stopped
    networks:
      - lapsusint-network

networks:
  lapsusint-network:
    driver: bridge 